import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { LinkButton } from "@/components/ui/link-button";
import { SampleBanner, SampleBadge } from "@/components/features/sample-banner";
import { sampleBlueprint, sampleWorkflow, isSampleId } from "@/lib/sample-data";
import {
  FileStack,
  Clock,
  TrendingDown,
  Zap,
  Sparkles,
  ArrowRight,
  CheckCircle2,
} from "lucide-react";

export default function BlueprintsPage() {
  // Sample blueprint data — will be replaced with Supabase query
  const blueprints = [
    {
      ...sampleBlueprint,
      workflow_name: sampleWorkflow.name,
    },
  ];

  return (
    <div className="space-y-6">
      {/* Sample data banner */}
      <SampleBanner />

      {/* Page header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Blueprints</h1>
          <p className="text-muted-foreground">
            AI-generated automation plans with ROI projections.
          </p>
        </div>
        <LinkButton href="/workflows">
          <Sparkles className="mr-2 h-4 w-4" />
          Generate from Workflow
        </LinkButton>
      </div>

      {blueprints.length === 0 ? (
        <Card>
          <CardContent>
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <div className="relative mb-4">
                <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-primary/15 to-primary/5">
                  <FileStack className="h-8 w-8 text-primary/60" />
                </div>
                <div className="absolute -top-1 -right-1 flex h-6 w-6 items-center justify-center rounded-full bg-primary/10">
                  <Sparkles className="h-3 w-3 text-primary" />
                </div>
              </div>
              <h3 className="text-xl font-semibold mb-1">No blueprints yet</h3>
              <p className="text-base text-muted-foreground max-w-md mb-5">
                Blueprints are generated from analyzed workflows. Map a workflow, then click &ldquo;Generate Blueprint&rdquo; to get a prioritized automation plan.
              </p>
              <LinkButton href="/workflows/new">
                <Sparkles className="mr-2 h-4 w-4" />
                Map a Workflow First
              </LinkButton>
            </div>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4">
          {blueprints.map((bp) => (
            <Card key={bp.id} className="group hover:shadow-sm transition-shadow">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <CardTitle>{bp.workflow_name}</CardTitle>
                      {isSampleId(bp.id) && <SampleBadge />}
                      <Badge variant="secondary" className="text-xs">
                        v{bp.version}
                      </Badge>
                    </div>
                    <CardDescription>
                      Generated by {bp.generated_by === "ai" ? "AI" : "manual review"} &middot;{" "}
                      {bp.recommended_automations.length} automations &middot;{" "}
                      {bp.implementation_sequence.length}-step implementation plan
                    </CardDescription>
                  </div>
                  <div className="flex items-center gap-2">
                    {bp.approved_by ? (
                      <Badge className="bg-green-100 text-green-700">
                        <CheckCircle2 className="h-3 w-3" />
                        Approved
                      </Badge>
                    ) : (
                      <Badge variant="outline" className="text-amber-600 border-amber-300">
                        Pending Approval
                      </Badge>
                    )}
                    <LinkButton href={`/blueprints/${bp.id}`} variant="outline" size="sm">
                      View Details
                      <ArrowRight className="ml-1 h-3 w-3" />
                    </LinkButton>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4 sm:grid-cols-3">
                  <div className="flex items-center gap-3 rounded-lg border p-3">
                    <Clock className="h-5 w-5 text-muted-foreground" />
                    <div>
                      <p className="text-xl font-bold">
                        {bp.expected_roi.hours_saved_monthly}
                      </p>
                      <p className="text-sm text-muted-foreground">
                        Hours saved / month
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3 rounded-lg border p-3">
                    <TrendingDown className="h-5 w-5 text-muted-foreground" />
                    <div>
                      <p className="text-xl font-bold">
                        {bp.expected_roi.cycle_time_reduction_pct}%
                      </p>
                      <p className="text-sm text-muted-foreground">
                        Cycle time reduction
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3 rounded-lg border p-3">
                    <Zap className="h-5 w-5 text-muted-foreground" />
                    <div>
                      <p className="text-xl font-bold">
                        {bp.expected_roi.error_rate_reduction_pct}%
                      </p>
                      <p className="text-sm text-muted-foreground">
                        Error rate reduction
                      </p>
                    </div>
                  </div>
                </div>

                {/* Automation summaries */}
                <div className="mt-4 space-y-2">
                  <p className="text-sm font-medium text-muted-foreground">
                    Recommended Automations
                  </p>
                  <div className="grid gap-2 sm:grid-cols-2">
                    {bp.recommended_automations.map((auto, i) => (
                      <div
                        key={i}
                        className="flex items-start gap-2 rounded-md border border-dashed p-2 text-sm"
                      >
                        <div className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-primary/10 text-[10px] font-bold text-primary">
                          {i + 1}
                        </div>
                        <div>
                          <p className="font-medium">{auto.title}</p>
                          <p className="text-muted-foreground line-clamp-1">
                            Replaces: {auto.steps_replaced.join(", ")}
                          </p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
