import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { LinkButton } from "@/components/ui/link-button";
import { Separator } from "@/components/ui/separator";
import { ExportPdfButton, ApproveBlueprintButton } from "./blueprint-actions";
import type { Blueprint, AutomationRecommendation } from "@/types";
import {
  ArrowLeft,
  Clock,
  GitBranch,
  Layers,
  TrendingDown,
  Zap,
  Rocket,
} from "lucide-react";
import { SampleBanner, SampleBadge } from "@/components/features/sample-banner";
import { sampleBlueprint, isSampleId } from "@/lib/sample-data";

function AutomationCard({
  automation,
  index,
}: {
  automation: AutomationRecommendation;
  index: number;
}) {
  return (
    <Card>
      <CardHeader>
        <div className="flex items-start gap-3">
          <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary text-primary-foreground text-xs font-bold">
            {index + 1}
          </div>
          <div>
            <CardTitle>{automation.title}</CardTitle>
            <CardDescription className="mt-1">
              {automation.description}
            </CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <div>
          <p className="text-sm font-medium text-muted-foreground mb-1.5">
            Steps Replaced
          </p>
          <div className="flex flex-wrap gap-1.5">
            {automation.steps_replaced.map((step) => (
              <Badge key={step} variant="secondary">
                {step}
              </Badge>
            ))}
          </div>
        </div>

        {automation.dependencies.length > 0 && (
          <div>
            <p className="text-sm font-medium text-muted-foreground mb-1.5">
              Dependencies
            </p>
            <div className="flex flex-wrap gap-1.5">
              {automation.dependencies.map((dep) => (
                <Badge key={dep} variant="outline">
                  <GitBranch className="h-3 w-3" />
                  {dep}
                </Badge>
              ))}
            </div>
          </div>
        )}

        <div>
          <p className="text-sm font-medium text-muted-foreground mb-1.5">
            Implementation Notes
          </p>
          <p className="text-base text-muted-foreground">
            {automation.implementation_notes}
          </p>
        </div>
      </CardContent>
    </Card>
  );
}

export default async function BlueprintPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  // Placeholder: in production, fetch blueprint by id
  const blueprint = sampleBlueprint;
  const isSample = isSampleId(id) || id === "sample-bp-001";

  return (
    <div className="space-y-6">
      {/* Sample data banner */}
      {isSample && <SampleBanner />}

      {/* Page header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <LinkButton href="/workflows" variant="ghost" size="icon">
            <ArrowLeft className="h-4 w-4" />
          </LinkButton>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-3xl font-bold tracking-tight">
                Automation Blueprint
              </h1>
              {isSample && <SampleBadge />}
            </div>
            <p className="text-muted-foreground">
              Blueprint #{id} &middot; Version {blueprint.version} &middot;
              Generated by{" "}
              {blueprint.generated_by === "ai" ? "AI" : "manual review"}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <LinkButton href="/deployments" variant="outline">
            <Rocket className="mr-2 h-4 w-4" />
            Create Sprint
          </LinkButton>
          <ExportPdfButton />
          <ApproveBlueprintButton
            approved={blueprint.approved_by !== null}
          />
        </div>
      </div>

      {/* ROI summary */}
      <div className="grid gap-4 sm:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-base font-medium">
              Hours Saved / Month
            </CardTitle>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {blueprint.expected_roi.hours_saved_monthly}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-base font-medium">
              Cycle Time Reduction
            </CardTitle>
            <TrendingDown className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {blueprint.expected_roi.cycle_time_reduction_pct}%
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-base font-medium">
              Error Rate Reduction
            </CardTitle>
            <Zap className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {blueprint.expected_roi.error_rate_reduction_pct}%
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Implementation Sequence */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Layers className="h-4 w-4" />
            Implementation Sequence
          </CardTitle>
          <CardDescription>
            Recommended order of implementation with dependency tracking.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ol className="relative space-y-3 border-l-2 border-border ml-3">
            {blueprint.implementation_sequence.map((step, i) => (
              <li key={i} className="ml-6 flex items-start gap-3">
                <div className="absolute -left-[9px] mt-0.5 h-4 w-4 rounded-full border-2 border-border bg-background" />
                <div>
                  <p className="text-base font-medium">{step}</p>
                  <p className="text-sm text-muted-foreground">
                    Step {i + 1} of{" "}
                    {blueprint.implementation_sequence.length}
                  </p>
                </div>
              </li>
            ))}
          </ol>
        </CardContent>
      </Card>

      <Separator />

      {/* Automations detail */}
      <div>
        <h2 className="text-xl font-semibold mb-4">
          Recommended Automations ({blueprint.recommended_automations.length})
        </h2>
        <div className="space-y-4">
          {blueprint.recommended_automations.map((automation, i) => (
            <AutomationCard key={i} automation={automation} index={i} />
          ))}
        </div>
      </div>
    </div>
  );
}
